kind: pipeline
type: kubernetes 
name: deploy

volumes:
  - name: dockersock
    temp: {}

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

steps:
  - name: build-app
    image: clojure:temurin-17-tools-deps-jammy
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_21.x | bash
      - apt-get update && apt-get install nodejs -y
      - npm ci
      - npx shadow-cljs release app
    when:
      branch:
        - main

  - name: build-push-docker
    image: docker:dind
    depends_on: [build-app]
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - docker buildx create --name samurai --use
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker buildx build . --push -t 1ocke/onboarding-app:${DRONE_COMMIT_SHA:0:7} -t 1ocke/onboarding-app:latest --platform linux/amd64,linux/arm64
    when:
      branch:
        - main

  - name: deploy-to-kubernetes
    image: bitnami/kubectl
    depends_on: [build-push-docker]
    environment:
      KUBE_CONFIG: {from_secret: kube_config}
    commands:
      - echo "$KUBE_CONFIG" > /.kube/config
      - kubectl -n zabelin rollout restart deployment/app
    when:
      branch:
        - main

  - name: notify-to-telegram
    image: appleboy/drone-telegram
    depends_on: [deploy-to-kubernetes]
    environment:
      TELEGRAM_TOKEN:
        from_secret: telegram_token
    when:
      status: [failure, success]
      branch:
        - main
    settings:
      disable_web_page_preview: true
      token: ${TELEGRAM_TOKEN}
      to: -4152454993
      message: |
        {{#success build.status}}
        ✅ {{repo.name}}:{{commit.branch}}
        {{else}}
        ❌ {{repo.name}}:{{commit.branch}}
        {{/success}}
        {{commit.message}} @{{commit.author}}
        {{build.link}}
